name: build and release

on:
  push:
    branches:
      - master
      - dev

    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yml"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - name: downlaod dependencies
        run: |
          go mod download
          go mod tidy -compat=1.17
        
      - name: build binary and package
        run: |
          go build -v -o v2ray -trimpath -ldflags "-s -w -buildid=" ./main
          curl -L -o geoip.dat "https://raw.githubusercontent.com/v2fly/geoip/release/geoip.dat"
          curl -L -o geoip-only-cn-private.dat "https://raw.githubusercontent.com/v2fly/geoip/release/geoip-only-cn-private.dat"
          curl -L -o geosite.dat "https://raw.githubusercontent.com/v2fly/domain-list-community/release/dlc.dat"
          zip -9vr v2ray-linux-64.zip v2ray *.dat
          
      - name: release binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty="format:%s" | grep -Ei '^bump version v[0-9]+\.[0-9]+\.[0-9]+$')
          if [ -n "$COMMIT_MESSAGE" ]; then
            BUMP_VERSION=$(git log -1 --pretty="format:%s" | grep -Eio 'v[0-9]+\.[0-9]+\.[0-9]+')
            echo "bump version to $BUMP_VERSION"
            gh release create ${BUMP_VERSION} -t ${BUMP_VERSION} -n "### New Version Was Released  \nuse at your own risk." *.zip
          else
            LATEST_TAG=$(git describe --tags --abbrev=0)
            test -n "$LATEST_TAG" || (echo "latest tag not found, exit." && exit 0)
            gh release upload --clobber ${LATEST_TAG} -t ${LATEST_TAG} *.zip
          fi