name: build and release

on:
  push:
    branches:
      - master
      - dev

    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yml"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - name: downlaod dependencies
        run: |
          go mod download
          go mod tidy -compat=1.17
        
      - name: build binary and packaging
        run: |
          go build -v -o v2ray -trimpath -ldflags "-s -w -buildid=" ./main
          curl -L -o geoip.dat "https://raw.githubusercontent.com/v2fly/geoip/release/geoip.dat"
          curl -L -o geoip-only-cn-private.dat "https://raw.githubusercontent.com/v2fly/geoip/release/geoip-only-cn-private.dat"
          curl -L -o geosite.dat "https://raw.githubusercontent.com/v2fly/domain-list-community/release/dlc.dat"
          zip -9vr v2ray-linux-64.zip v2ray *.dat
          
      - name: release binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload --clobber v1.0.0 *.zip